# Generated by Django 2.0.6 on 2018-07-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180629_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'public'), ('1', 'private')], default=('0', 'public'), max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='visiable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Visiable'),
        ),
    ]
