# Generated by Django 2.0.6 on 2018-07-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180708_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiable',
            name='name',
        ),
    ]
