# Generated by Django 2.0.6 on 2018-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_visiable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiable',
            name='name',
            field=models.CharField(choices=[('0', 'public'), ('1', 'private')], default=('0', 'public'), max_length=100),
        ),
    ]
