# Generated by Django 2.1.5 on 2019-10-14 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
