# Generated by Django 2.2.13 on 2021-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=100),
        ),
    ]
